steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - s1-ad-hourly
      - --source=.
      - --region=us-central1
      - --project=carbon-storm-422904-n0
      # (no --set-env-vars here; we’ll keep envs on the job)

options:
  logging: CLOUD_LOGGING_ONLY
  # or:
  # defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET


